package org.blbulyandavbulyan.oeadl.interfaces;

public interface EditorDialogControllingInterface extends SetVisibleInterface, SetActionAfterOkButtonPressed, SetActionAfterCancelButtonPressedInterface, GetValue, DisposeInterface{
}
